package com.dao;

import com.bean.AccessGroup;
import com.bean.AccessGroupWithBLOBs;

/**
 * @version 2017/6/29.
 * @auther CrazyBunQnQ
 */
public interface AccessGroupDao extends BaseDao<AccessGroupWithBLOBs> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_access_group
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_access_group
     *
     * @mbg.generated
     */
    int insert(AccessGroupWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_access_group
     *
     * @mbg.generated
     */
    int insertSelective(AccessGroupWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_access_group
     *
     * @mbg.generated
     */
    AccessGroupWithBLOBs selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_access_group
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AccessGroupWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_access_group
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(AccessGroupWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_access_group
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AccessGroup record);
}