package com.dao;

import com.bean.AccessGroup;

/**
 * @version 2017/6/29.
 * @auther CrazyBunQnQ
 */
public interface AccessGroupDao extends BaseDao<AccessGroup> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_access_group
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_access_group
     *
     * @mbg.generated
     */
    int insert(AccessGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_access_group
     *
     * @mbg.generated
     */
    int insertSelective(AccessGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_access_group
     *
     * @mbg.generated
     */
    AccessGroup selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_access_group
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AccessGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_access_group
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(AccessGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_access_group
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AccessGroup record);
}