package com.dao;

import com.bean.C3p0TestTable;

public interface C3p0TestTableDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c3p0testtable
     *
     * @mbg.generated
     */
    int insert(C3p0TestTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c3p0testtable
     *
     * @mbg.generated
     */
    int insertSelective(C3p0TestTable record);
}