package com.dao;

import com.bean.City;

/**
 * @version 2017/6/29.
 * @auther CrazyBunQnQ
 */
public interface CityDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_city
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_city
     *
     * @mbg.generated
     */
    int insert(City record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_city
     *
     * @mbg.generated
     */
    int insertSelective(City record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_city
     *
     * @mbg.generated
     */
    City selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_city
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(City record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_city
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(City record);
}