package com.dao;

import com.bean.CompanyTouch;
import com.bean.CompanyTouchWithBLOBs;

/**
 * @version 2017/6/29.
 * @auther CrazyBunQnQ
 */
public interface CompanyTouchDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_company_touch
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_company_touch
     *
     * @mbg.generated
     */
    int insert(CompanyTouchWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_company_touch
     *
     * @mbg.generated
     */
    int insertSelective(CompanyTouchWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_company_touch
     *
     * @mbg.generated
     */
    CompanyTouchWithBLOBs selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_company_touch
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CompanyTouchWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_company_touch
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(CompanyTouchWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_company_touch
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CompanyTouch record);
}