package com.dao;

import com.bean.Company;
import com.bean.CompanyWithBLOBs;

public interface CompanyDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_company
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_company
     *
     * @mbg.generated
     */
    int insert(CompanyWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_company
     *
     * @mbg.generated
     */
    int insertSelective(CompanyWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_company
     *
     * @mbg.generated
     */
    CompanyWithBLOBs selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_company
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CompanyWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_company
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(CompanyWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_company
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Company record);
}