package com.dao;

import com.bean.DictionaryDetail;

public interface DictionaryDetailDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_dictionary_detail
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_dictionary_detail
     *
     * @mbg.generated
     */
    int insert(DictionaryDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_dictionary_detail
     *
     * @mbg.generated
     */
    int insertSelective(DictionaryDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_dictionary_detail
     *
     * @mbg.generated
     */
    DictionaryDetail selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_dictionary_detail
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DictionaryDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_dictionary_detail
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(DictionaryDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_dictionary_detail
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DictionaryDetail record);
}