package com.dao;

import com.bean.Gather;
import com.bean.GatherWithBLOBs;

/**
 * @version 2017/6/29.
 * @auther CrazyBunQnQ
 */
public interface GatherDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_gather
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_gather
     *
     * @mbg.generated
     */
    int insert(GatherWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_gather
     *
     * @mbg.generated
     */
    int insertSelective(GatherWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_gather
     *
     * @mbg.generated
     */
    GatherWithBLOBs selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_gather
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(GatherWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_gather
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(GatherWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_gather
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Gather record);
}