package com.dao;

import com.bean.NeedGather;
import com.bean.NeedGatherWithBLOBs;

/**
 * @version 2017/6/29.
 * @auther CrazyBunQnQ
 */
public interface NeedGatherDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_need_gather
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_need_gather
     *
     * @mbg.generated
     */
    int insert(NeedGatherWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_need_gather
     *
     * @mbg.generated
     */
    int insertSelective(NeedGatherWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_need_gather
     *
     * @mbg.generated
     */
    NeedGatherWithBLOBs selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_need_gather
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(NeedGatherWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_need_gather
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(NeedGatherWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_need_gather
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(NeedGather record);
}