package com.dao;

import com.bean.Order;
import com.bean.OrderWithBLOBs;

/**
 * @version 2017/6/29.
 * @auther CrazyBunQnQ
 */
public interface OrderDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_order
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_order
     *
     * @mbg.generated
     */
    int insert(OrderWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_order
     *
     * @mbg.generated
     */
    int insertSelective(OrderWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_order
     *
     * @mbg.generated
     */
    OrderWithBLOBs selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(OrderWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(OrderWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Order record);
}