package com.dao;

import com.bean.ProductType;

public interface ProductTypeDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_product_type
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_product_type
     *
     * @mbg.generated
     */
    int insert(ProductType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_product_type
     *
     * @mbg.generated
     */
    int insertSelective(ProductType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_product_type
     *
     * @mbg.generated
     */
    ProductType selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_product_type
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ProductType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_product_type
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(ProductType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_product_type
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ProductType record);
}