package com.dao;

import com.bean.UserGroup;

/**
 * @version 2017/6/29.
 * @auther CrazyBunQnQ
 */
public interface UserGroupDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_user_group
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_user_group
     *
     * @mbg.generated
     */
    int insert(UserGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_user_group
     *
     * @mbg.generated
     */
    int insertSelective(UserGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_user_group
     *
     * @mbg.generated
     */
    UserGroup selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_user_group
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(UserGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_user_group
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(UserGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_user_group
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UserGroup record);
}