package com.bean;

import lombok.Data;

import java.util.Date;

@Data
public class CompanyLinkman {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_company_linkman.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_company_linkman.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_company_linkman.pycode
     *
     * @mbg.generated
     */
    private String pycode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_company_linkman.code
     *
     * @mbg.generated
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_company_linkman.sex
     *
     * @mbg.generated
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_company_linkman.birthday
     *
     * @mbg.generated
     */
    private Date birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_company_linkman.department
     *
     * @mbg.generated
     */
    private String department;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_company_linkman.duty
     *
     * @mbg.generated
     */
    private String duty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_company_linkman.office_tel
     *
     * @mbg.generated
     */
    private String officeTel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_company_linkman.home_tel
     *
     * @mbg.generated
     */
    private String homeTel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_company_linkman.mobile
     *
     * @mbg.generated
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_company_linkman.email
     *
     * @mbg.generated
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_company_linkman.qq_num
     *
     * @mbg.generated
     */
    private String qqNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_company_linkman.qq_name
     *
     * @mbg.generated
     */
    private String qqName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_company_linkman.postcode
     *
     * @mbg.generated
     */
    private String postcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_company_linkman.address
     *
     * @mbg.generated
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_company_linkman.fax
     *
     * @mbg.generated
     */
    private String fax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_company_linkman.other_link
     *
     * @mbg.generated
     */
    private String otherLink;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_company_linkman.hobby
     *
     * @mbg.generated
     */
    private String hobby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_company_linkman.taboo
     *
     * @mbg.generated
     */
    private String taboo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_company_linkman.main_flag
     *
     * @mbg.generated
     */
    private String mainFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_company_linkman.creater
     *
     * @mbg.generated
     */
    private String creater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_company_linkman.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_company_linkman.updater
     *
     * @mbg.generated
     */
    private String updater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_company_linkman.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_company_linkman.custom1
     *
     * @mbg.generated
     */
    private String custom1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_company_linkman.custom2
     *
     * @mbg.generated
     */
    private String custom2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_company_linkman.custom3
     *
     * @mbg.generated
     */
    private String custom3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_company_linkman.custom4
     *
     * @mbg.generated
     */
    private String custom4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_company_linkman.choice1
     *
     * @mbg.generated
     */
    private String choice1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_company_linkman.choice2
     *
     * @mbg.generated
     */
    private String choice2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_company_linkman.choice3
     *
     * @mbg.generated
     */
    private String choice3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_company_linkman.choice4
     *
     * @mbg.generated
     */
    private String choice4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_company_linkman.time1
     *
     * @mbg.generated
     */
    private Date time1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_company_linkman.time2
     *
     * @mbg.generated
     */
    private Date time2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_company_linkman.m_type
     *
     * @mbg.generated
     */
    private String mType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_company_linkman.share_flag
     *
     * @mbg.generated
     */
    private String shareFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_company_linkman.c_id
     *
     * @mbg.generated
     */
    private Integer cId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_company_linkman.owner_usr
     *
     * @mbg.generated
     */
    private Integer ownerUsr;

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_company_linkman.name
     *
     * @param name the value for c_company_linkman.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_company_linkman.pycode
     *
     * @param pycode the value for c_company_linkman.pycode
     *
     * @mbg.generated
     */
    public void setPycode(String pycode) {
        this.pycode = pycode == null ? null : pycode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_company_linkman.code
     *
     * @param code the value for c_company_linkman.code
     *
     * @mbg.generated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_company_linkman.sex
     *
     * @param sex the value for c_company_linkman.sex
     *
     * @mbg.generated
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_company_linkman.department
     *
     * @param department the value for c_company_linkman.department
     *
     * @mbg.generated
     */
    public void setDepartment(String department) {
        this.department = department == null ? null : department.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_company_linkman.duty
     *
     * @param duty the value for c_company_linkman.duty
     *
     * @mbg.generated
     */
    public void setDuty(String duty) {
        this.duty = duty == null ? null : duty.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_company_linkman.office_tel
     *
     * @param officeTel the value for c_company_linkman.office_tel
     *
     * @mbg.generated
     */
    public void setOfficeTel(String officeTel) {
        this.officeTel = officeTel == null ? null : officeTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_company_linkman.home_tel
     *
     * @param homeTel the value for c_company_linkman.home_tel
     *
     * @mbg.generated
     */
    public void setHomeTel(String homeTel) {
        this.homeTel = homeTel == null ? null : homeTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_company_linkman.mobile
     *
     * @param mobile the value for c_company_linkman.mobile
     *
     * @mbg.generated
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_company_linkman.email
     *
     * @param email the value for c_company_linkman.email
     *
     * @mbg.generated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_company_linkman.qq_num
     *
     * @param qqNum the value for c_company_linkman.qq_num
     *
     * @mbg.generated
     */
    public void setQqNum(String qqNum) {
        this.qqNum = qqNum == null ? null : qqNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_company_linkman.qq_name
     *
     * @param qqName the value for c_company_linkman.qq_name
     *
     * @mbg.generated
     */
    public void setQqName(String qqName) {
        this.qqName = qqName == null ? null : qqName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_company_linkman.postcode
     *
     * @param postcode the value for c_company_linkman.postcode
     *
     * @mbg.generated
     */
    public void setPostcode(String postcode) {
        this.postcode = postcode == null ? null : postcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_company_linkman.address
     *
     * @param address the value for c_company_linkman.address
     *
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_company_linkman.fax
     *
     * @param fax the value for c_company_linkman.fax
     *
     * @mbg.generated
     */
    public void setFax(String fax) {
        this.fax = fax == null ? null : fax.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_company_linkman.other_link
     *
     * @param otherLink the value for c_company_linkman.other_link
     *
     * @mbg.generated
     */
    public void setOtherLink(String otherLink) {
        this.otherLink = otherLink == null ? null : otherLink.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_company_linkman.hobby
     *
     * @param hobby the value for c_company_linkman.hobby
     *
     * @mbg.generated
     */
    public void setHobby(String hobby) {
        this.hobby = hobby == null ? null : hobby.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_company_linkman.taboo
     *
     * @param taboo the value for c_company_linkman.taboo
     *
     * @mbg.generated
     */
    public void setTaboo(String taboo) {
        this.taboo = taboo == null ? null : taboo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_company_linkman.main_flag
     *
     * @param mainFlag the value for c_company_linkman.main_flag
     *
     * @mbg.generated
     */
    public void setMainFlag(String mainFlag) {
        this.mainFlag = mainFlag == null ? null : mainFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_company_linkman.creater
     *
     * @param creater the value for c_company_linkman.creater
     *
     * @mbg.generated
     */
    public void setCreater(String creater) {
        this.creater = creater == null ? null : creater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_company_linkman.updater
     *
     * @param updater the value for c_company_linkman.updater
     *
     * @mbg.generated
     */
    public void setUpdater(String updater) {
        this.updater = updater == null ? null : updater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_company_linkman.update_time
     *
     * @param updateTime the value for c_company_linkman.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_company_linkman.custom1
     *
     * @param custom1 the value for c_company_linkman.custom1
     *
     * @mbg.generated
     */
    public void setCustom1(String custom1) {
        this.custom1 = custom1 == null ? null : custom1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_company_linkman.custom2
     *
     * @param custom2 the value for c_company_linkman.custom2
     *
     * @mbg.generated
     */
    public void setCustom2(String custom2) {
        this.custom2 = custom2 == null ? null : custom2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_company_linkman.custom3
     *
     * @param custom3 the value for c_company_linkman.custom3
     *
     * @mbg.generated
     */
    public void setCustom3(String custom3) {
        this.custom3 = custom3 == null ? null : custom3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_company_linkman.custom4
     *
     * @param custom4 the value for c_company_linkman.custom4
     *
     * @mbg.generated
     */
    public void setCustom4(String custom4) {
        this.custom4 = custom4 == null ? null : custom4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_company_linkman.choice1
     *
     * @param choice1 the value for c_company_linkman.choice1
     *
     * @mbg.generated
     */
    public void setChoice1(String choice1) {
        this.choice1 = choice1 == null ? null : choice1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_company_linkman.choice2
     *
     * @param choice2 the value for c_company_linkman.choice2
     *
     * @mbg.generated
     */
    public void setChoice2(String choice2) {
        this.choice2 = choice2 == null ? null : choice2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_company_linkman.choice3
     *
     * @param choice3 the value for c_company_linkman.choice3
     *
     * @mbg.generated
     */
    public void setChoice3(String choice3) {
        this.choice3 = choice3 == null ? null : choice3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_company_linkman.choice4
     *
     * @param choice4 the value for c_company_linkman.choice4
     *
     * @mbg.generated
     */
    public void setChoice4(String choice4) {
        this.choice4 = choice4 == null ? null : choice4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_company_linkman.m_type
     *
     * @param mType the value for c_company_linkman.m_type
     *
     * @mbg.generated
     */
    public void setmType(String mType) {
        this.mType = mType == null ? null : mType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_company_linkman.share_flag
     *
     * @param shareFlag the value for c_company_linkman.share_flag
     *
     * @mbg.generated
     */
    public void setShareFlag(String shareFlag) {
        this.shareFlag = shareFlag == null ? null : shareFlag.trim();
    }
}