package com.bean;

import lombok.Data;

import java.util.Date;

@Data
public class Company {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_company.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_company.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_company.pycode
     *
     * @mbg.generated
     */
    private String pycode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_company.code
     *
     * @mbg.generated
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_company.grade
     *
     * @mbg.generated
     */
    private String grade;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_company.source
     *
     * @mbg.generated
     */
    private String source;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_company.c_type
     *
     * @mbg.generated
     */
    private String cType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_company.m_type
     *
     * @mbg.generated
     */
    private String mType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_company.region_id
     *
     * @mbg.generated
     */
    private Integer regionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_company.region_name
     *
     * @mbg.generated
     */
    private String regionName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_company.province
     *
     * @mbg.generated
     */
    private String province;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_company.city
     *
     * @mbg.generated
     */
    private String city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_company.fax
     *
     * @mbg.generated
     */
    private String fax;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_company.postcode
     *
     * @mbg.generated
     */
    private String postcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_company.tel1
     *
     * @mbg.generated
     */
    private String tel1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_company.tel2
     *
     * @mbg.generated
     */
    private String tel2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_company.mobile
     *
     * @mbg.generated
     */
    private String mobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_company.email
     *
     * @mbg.generated
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_company.web
     *
     * @mbg.generated
     */
    private String web;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_company.address
     *
     * @mbg.generated
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_company.dealing
     *
     * @mbg.generated
     */
    private String dealing;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_company.scale
     *
     * @mbg.generated
     */
    private String scale;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_company.register_money
     *
     * @mbg.generated
     */
    private String registerMoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_company.kind
     *
     * @mbg.generated
     */
    private String kind;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_company.trade
     *
     * @mbg.generated
     */
    private String trade;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_company.legal_person
     *
     * @mbg.generated
     */
    private String legalPerson;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_company.bank
     *
     * @mbg.generated
     */
    private String bank;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_company.account
     *
     * @mbg.generated
     */
    private String account;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_company.tax_code
     *
     * @mbg.generated
     */
    private String taxCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_company.buy_flag
     *
     * @mbg.generated
     */
    private String buyFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_company.creater
     *
     * @mbg.generated
     */
    private String creater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_company.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_company.updater
     *
     * @mbg.generated
     */
    private String updater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_company.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_company.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_company.next_touch_date
     *
     * @mbg.generated
     */
    private Date nextTouchDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_company.next_service_date
     *
     * @mbg.generated
     */
    private Date nextServiceDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_company.first_touch_date
     *
     * @mbg.generated
     */
    private Date firstTouchDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_company.last_touch_date
     *
     * @mbg.generated
     */
    private Date lastTouchDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_company.dispense_person
     *
     * @mbg.generated
     */
    private String dispensePerson;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_company.dispense_date
     *
     * @mbg.generated
     */
    private Date dispenseDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_company.apply_user_id
     *
     * @mbg.generated
     */
    private Integer applyUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_company.s_person
     *
     * @mbg.generated
     */
    private String sPerson;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_company.s_date
     *
     * @mbg.generated
     */
    private Date sDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_company.plan_callback_date
     *
     * @mbg.generated
     */
    private Date planCallbackDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_company.cur_link_flag
     *
     * @mbg.generated
     */
    private String curLinkFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_company.cur_buy_flag
     *
     * @mbg.generated
     */
    private String curBuyFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_company.freeze_leave_day
     *
     * @mbg.generated
     */
    private Integer freezeLeaveDay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_company.custom1
     *
     * @mbg.generated
     */
    private String custom1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_company.custom2
     *
     * @mbg.generated
     */
    private String custom2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_company.custom3
     *
     * @mbg.generated
     */
    private String custom3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_company.custom4
     *
     * @mbg.generated
     */
    private String custom4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_company.choice1
     *
     * @mbg.generated
     */
    private String choice1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_company.choice2
     *
     * @mbg.generated
     */
    private String choice2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_company.choice3
     *
     * @mbg.generated
     */
    private String choice3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_company.choice4
     *
     * @mbg.generated
     */
    private String choice4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_company.time1
     *
     * @mbg.generated
     */
    private Date time1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_company.time2
     *
     * @mbg.generated
     */
    private Date time2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_company.share_flag
     *
     * @mbg.generated
     */
    private String shareFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_company.quality
     *
     * @mbg.generated
     */
    private String quality;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_company.owner_usr
     *
     * @mbg.generated
     */
    private Integer ownerUsr;

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_company.name
     *
     * @param name the value for c_company.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_company.pycode
     *
     * @param pycode the value for c_company.pycode
     *
     * @mbg.generated
     */
    public void setPycode(String pycode) {
        this.pycode = pycode == null ? null : pycode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_company.code
     *
     * @param code the value for c_company.code
     *
     * @mbg.generated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_company.grade
     *
     * @param grade the value for c_company.grade
     *
     * @mbg.generated
     */
    public void setGrade(String grade) {
        this.grade = grade == null ? null : grade.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_company.source
     *
     * @param source the value for c_company.source
     *
     * @mbg.generated
     */
    public void setSource(String source) {
        this.source = source == null ? null : source.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_company.c_type
     *
     * @param cType the value for c_company.c_type
     *
     * @mbg.generated
     */
    public void setcType(String cType) {
        this.cType = cType == null ? null : cType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_company.m_type
     *
     * @param mType the value for c_company.m_type
     *
     * @mbg.generated
     */
    public void setmType(String mType) {
        this.mType = mType == null ? null : mType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_company.region_id
     *
     * @param regionId the value for c_company.region_id
     *
     * @mbg.generated
     */
    public void setRegionId(Integer regionId) {
        this.regionId = regionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_company.region_name
     *
     * @param regionName the value for c_company.region_name
     *
     * @mbg.generated
     */
    public void setRegionName(String regionName) {
        this.regionName = regionName == null ? null : regionName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_company.province
     *
     * @param province the value for c_company.province
     *
     * @mbg.generated
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_company.city
     *
     * @param city the value for c_company.city
     *
     * @mbg.generated
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_company.fax
     *
     * @param fax the value for c_company.fax
     *
     * @mbg.generated
     */
    public void setFax(String fax) {
        this.fax = fax == null ? null : fax.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_company.postcode
     *
     * @param postcode the value for c_company.postcode
     *
     * @mbg.generated
     */
    public void setPostcode(String postcode) {
        this.postcode = postcode == null ? null : postcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_company.tel1
     *
     * @param tel1 the value for c_company.tel1
     *
     * @mbg.generated
     */
    public void setTel1(String tel1) {
        this.tel1 = tel1 == null ? null : tel1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_company.tel2
     *
     * @param tel2 the value for c_company.tel2
     *
     * @mbg.generated
     */
    public void setTel2(String tel2) {
        this.tel2 = tel2 == null ? null : tel2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_company.mobile
     *
     * @param mobile the value for c_company.mobile
     *
     * @mbg.generated
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_company.email
     *
     * @param email the value for c_company.email
     *
     * @mbg.generated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_company.web
     *
     * @param web the value for c_company.web
     *
     * @mbg.generated
     */
    public void setWeb(String web) {
        this.web = web == null ? null : web.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_company.address
     *
     * @param address the value for c_company.address
     *
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_company.dealing
     *
     * @param dealing the value for c_company.dealing
     *
     * @mbg.generated
     */
    public void setDealing(String dealing) {
        this.dealing = dealing == null ? null : dealing.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_company.scale
     *
     * @param scale the value for c_company.scale
     *
     * @mbg.generated
     */
    public void setScale(String scale) {
        this.scale = scale == null ? null : scale.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_company.register_money
     *
     * @param registerMoney the value for c_company.register_money
     *
     * @mbg.generated
     */
    public void setRegisterMoney(String registerMoney) {
        this.registerMoney = registerMoney == null ? null : registerMoney.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_company.kind
     *
     * @param kind the value for c_company.kind
     *
     * @mbg.generated
     */
    public void setKind(String kind) {
        this.kind = kind == null ? null : kind.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_company.trade
     *
     * @param trade the value for c_company.trade
     *
     * @mbg.generated
     */
    public void setTrade(String trade) {
        this.trade = trade == null ? null : trade.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_company.legal_person
     *
     * @param legalPerson the value for c_company.legal_person
     *
     * @mbg.generated
     */
    public void setLegalPerson(String legalPerson) {
        this.legalPerson = legalPerson == null ? null : legalPerson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_company.bank
     *
     * @param bank the value for c_company.bank
     *
     * @mbg.generated
     */
    public void setBank(String bank) {
        this.bank = bank == null ? null : bank.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_company.account
     *
     * @param account the value for c_company.account
     *
     * @mbg.generated
     */
    public void setAccount(String account) {
        this.account = account == null ? null : account.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_company.tax_code
     *
     * @param taxCode the value for c_company.tax_code
     *
     * @mbg.generated
     */
    public void setTaxCode(String taxCode) {
        this.taxCode = taxCode == null ? null : taxCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_company.buy_flag
     *
     * @param buyFlag the value for c_company.buy_flag
     *
     * @mbg.generated
     */
    public void setBuyFlag(String buyFlag) {
        this.buyFlag = buyFlag == null ? null : buyFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_company.creater
     *
     * @param creater the value for c_company.creater
     *
     * @mbg.generated
     */
    public void setCreater(String creater) {
        this.creater = creater == null ? null : creater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_company.updater
     *
     * @param updater the value for c_company.updater
     *
     * @mbg.generated
     */
    public void setUpdater(String updater) {
        this.updater = updater == null ? null : updater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_company.status
     *
     * @param status the value for c_company.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_company.next_touch_date
     *
     * @param nextTouchDate the value for c_company.next_touch_date
     *
     * @mbg.generated
     */
    public void setNextTouchDate(Date nextTouchDate) {
        this.nextTouchDate = nextTouchDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_company.dispense_person
     *
     * @param dispensePerson the value for c_company.dispense_person
     *
     * @mbg.generated
     */
    public void setDispensePerson(String dispensePerson) {
        this.dispensePerson = dispensePerson == null ? null : dispensePerson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_company.s_person
     *
     * @param sPerson the value for c_company.s_person
     *
     * @mbg.generated
     */
    public void setsPerson(String sPerson) {
        this.sPerson = sPerson == null ? null : sPerson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_company.cur_link_flag
     *
     * @param curLinkFlag the value for c_company.cur_link_flag
     *
     * @mbg.generated
     */
    public void setCurLinkFlag(String curLinkFlag) {
        this.curLinkFlag = curLinkFlag == null ? null : curLinkFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_company.cur_buy_flag
     *
     * @param curBuyFlag the value for c_company.cur_buy_flag
     *
     * @mbg.generated
     */
    public void setCurBuyFlag(String curBuyFlag) {
        this.curBuyFlag = curBuyFlag == null ? null : curBuyFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_company.custom1
     *
     * @param custom1 the value for c_company.custom1
     *
     * @mbg.generated
     */
    public void setCustom1(String custom1) {
        this.custom1 = custom1 == null ? null : custom1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_company.custom2
     *
     * @param custom2 the value for c_company.custom2
     *
     * @mbg.generated
     */
    public void setCustom2(String custom2) {
        this.custom2 = custom2 == null ? null : custom2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_company.custom3
     *
     * @param custom3 the value for c_company.custom3
     *
     * @mbg.generated
     */
    public void setCustom3(String custom3) {
        this.custom3 = custom3 == null ? null : custom3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_company.custom4
     *
     * @param custom4 the value for c_company.custom4
     *
     * @mbg.generated
     */
    public void setCustom4(String custom4) {
        this.custom4 = custom4 == null ? null : custom4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_company.choice1
     *
     * @param choice1 the value for c_company.choice1
     *
     * @mbg.generated
     */
    public void setChoice1(String choice1) {
        this.choice1 = choice1 == null ? null : choice1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_company.choice2
     *
     * @param choice2 the value for c_company.choice2
     *
     * @mbg.generated
     */
    public void setChoice2(String choice2) {
        this.choice2 = choice2 == null ? null : choice2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_company.choice3
     *
     * @param choice3 the value for c_company.choice3
     *
     * @mbg.generated
     */
    public void setChoice3(String choice3) {
        this.choice3 = choice3 == null ? null : choice3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_company.choice4
     *
     * @param choice4 the value for c_company.choice4
     *
     * @mbg.generated
     */
    public void setChoice4(String choice4) {
        this.choice4 = choice4 == null ? null : choice4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_company.share_flag
     *
     * @param shareFlag the value for c_company.share_flag
     *
     * @mbg.generated
     */
    public void setShareFlag(String shareFlag) {
        this.shareFlag = shareFlag == null ? null : shareFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_company.quality
     *
     * @param quality the value for c_company.quality
     *
     * @mbg.generated
     */
    public void setQuality(String quality) {
        this.quality = quality == null ? null : quality.trim();
    }
}