package com.bean;

public class CompanyWithBLOBs extends Company {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_company.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_company.next_touch_aim
     *
     * @mbg.generated
     */
    private String nextTouchAim;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_company.s_reason
     *
     * @mbg.generated
     */
    private String sReason;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_company.plan_callback_reason
     *
     * @mbg.generated
     */
    private String planCallbackReason;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_company.share_ids
     *
     * @mbg.generated
     */
    private String shareIds;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_company.remark
     *
     * @return the value of c_company.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_company.remark
     *
     * @param remark the value for c_company.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_company.next_touch_aim
     *
     * @return the value of c_company.next_touch_aim
     *
     * @mbg.generated
     */
    public String getNextTouchAim() {
        return nextTouchAim;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_company.next_touch_aim
     *
     * @param nextTouchAim the value for c_company.next_touch_aim
     *
     * @mbg.generated
     */
    public void setNextTouchAim(String nextTouchAim) {
        this.nextTouchAim = nextTouchAim == null ? null : nextTouchAim.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_company.s_reason
     *
     * @return the value of c_company.s_reason
     *
     * @mbg.generated
     */
    public String getsReason() {
        return sReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_company.s_reason
     *
     * @param sReason the value for c_company.s_reason
     *
     * @mbg.generated
     */
    public void setsReason(String sReason) {
        this.sReason = sReason == null ? null : sReason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_company.plan_callback_reason
     *
     * @return the value of c_company.plan_callback_reason
     *
     * @mbg.generated
     */
    public String getPlanCallbackReason() {
        return planCallbackReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_company.plan_callback_reason
     *
     * @param planCallbackReason the value for c_company.plan_callback_reason
     *
     * @mbg.generated
     */
    public void setPlanCallbackReason(String planCallbackReason) {
        this.planCallbackReason = planCallbackReason == null ? null : planCallbackReason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_company.share_ids
     *
     * @return the value of c_company.share_ids
     *
     * @mbg.generated
     */
    public String getShareIds() {
        return shareIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_company.share_ids
     *
     * @param shareIds the value for c_company.share_ids
     *
     * @mbg.generated
     */
    public void setShareIds(String shareIds) {
        this.shareIds = shareIds == null ? null : shareIds.trim();
    }
}