package com.bean;

import java.util.Date;

public class CompanyTouch {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_company_touch.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_company_touch.c_id
     *
     * @mbg.generated
     */
    private Integer cId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_company_touch.link_man
     *
     * @mbg.generated
     */
    private String linkMan;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_company_touch.link_fashion
     *
     * @mbg.generated
     */
    private String linkFashion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_company_touch.link_type
     *
     * @mbg.generated
     */
    private String linkType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_company_touch.link_time
     *
     * @mbg.generated
     */
    private Date linkTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_company_touch.user_name
     *
     * @mbg.generated
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_company_touch.next_touch_date
     *
     * @mbg.generated
     */
    private Date nextTouchDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_company_touch.creater
     *
     * @mbg.generated
     */
    private String creater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_company_touch.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_company_touch.updater
     *
     * @mbg.generated
     */
    private String updater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_company_touch.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_company_touch.custom1
     *
     * @mbg.generated
     */
    private String custom1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_company_touch.custom2
     *
     * @mbg.generated
     */
    private String custom2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_company_touch.custom3
     *
     * @mbg.generated
     */
    private String custom3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_company_touch.custom4
     *
     * @mbg.generated
     */
    private String custom4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_company_touch.choice1
     *
     * @mbg.generated
     */
    private String choice1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_company_touch.choice2
     *
     * @mbg.generated
     */
    private String choice2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_company_touch.choice3
     *
     * @mbg.generated
     */
    private String choice3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_company_touch.choice4
     *
     * @mbg.generated
     */
    private String choice4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_company_touch.time1
     *
     * @mbg.generated
     */
    private Date time1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_company_touch.time2
     *
     * @mbg.generated
     */
    private Date time2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_company_touch.m_type
     *
     * @mbg.generated
     */
    private String mType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_company_touch.share_flag
     *
     * @mbg.generated
     */
    private String shareFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column c_company_touch.owner_usr
     *
     * @mbg.generated
     */
    private Integer ownerUsr;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_company_touch.id
     *
     * @return the value of c_company_touch.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_company_touch.id
     *
     * @param id the value for c_company_touch.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_company_touch.c_id
     *
     * @return the value of c_company_touch.c_id
     *
     * @mbg.generated
     */
    public Integer getcId() {
        return cId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_company_touch.c_id
     *
     * @param cId the value for c_company_touch.c_id
     *
     * @mbg.generated
     */
    public void setcId(Integer cId) {
        this.cId = cId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_company_touch.link_man
     *
     * @return the value of c_company_touch.link_man
     *
     * @mbg.generated
     */
    public String getLinkMan() {
        return linkMan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_company_touch.link_man
     *
     * @param linkMan the value for c_company_touch.link_man
     *
     * @mbg.generated
     */
    public void setLinkMan(String linkMan) {
        this.linkMan = linkMan == null ? null : linkMan.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_company_touch.link_fashion
     *
     * @return the value of c_company_touch.link_fashion
     *
     * @mbg.generated
     */
    public String getLinkFashion() {
        return linkFashion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_company_touch.link_fashion
     *
     * @param linkFashion the value for c_company_touch.link_fashion
     *
     * @mbg.generated
     */
    public void setLinkFashion(String linkFashion) {
        this.linkFashion = linkFashion == null ? null : linkFashion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_company_touch.link_type
     *
     * @return the value of c_company_touch.link_type
     *
     * @mbg.generated
     */
    public String getLinkType() {
        return linkType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_company_touch.link_type
     *
     * @param linkType the value for c_company_touch.link_type
     *
     * @mbg.generated
     */
    public void setLinkType(String linkType) {
        this.linkType = linkType == null ? null : linkType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_company_touch.link_time
     *
     * @return the value of c_company_touch.link_time
     *
     * @mbg.generated
     */
    public Date getLinkTime() {
        return linkTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_company_touch.link_time
     *
     * @param linkTime the value for c_company_touch.link_time
     *
     * @mbg.generated
     */
    public void setLinkTime(Date linkTime) {
        this.linkTime = linkTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_company_touch.user_name
     *
     * @return the value of c_company_touch.user_name
     *
     * @mbg.generated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_company_touch.user_name
     *
     * @param userName the value for c_company_touch.user_name
     *
     * @mbg.generated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_company_touch.next_touch_date
     *
     * @return the value of c_company_touch.next_touch_date
     *
     * @mbg.generated
     */
    public Date getNextTouchDate() {
        return nextTouchDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_company_touch.next_touch_date
     *
     * @param nextTouchDate the value for c_company_touch.next_touch_date
     *
     * @mbg.generated
     */
    public void setNextTouchDate(Date nextTouchDate) {
        this.nextTouchDate = nextTouchDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_company_touch.creater
     *
     * @return the value of c_company_touch.creater
     *
     * @mbg.generated
     */
    public String getCreater() {
        return creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_company_touch.creater
     *
     * @param creater the value for c_company_touch.creater
     *
     * @mbg.generated
     */
    public void setCreater(String creater) {
        this.creater = creater == null ? null : creater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_company_touch.create_time
     *
     * @return the value of c_company_touch.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_company_touch.create_time
     *
     * @param createTime the value for c_company_touch.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_company_touch.updater
     *
     * @return the value of c_company_touch.updater
     *
     * @mbg.generated
     */
    public String getUpdater() {
        return updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_company_touch.updater
     *
     * @param updater the value for c_company_touch.updater
     *
     * @mbg.generated
     */
    public void setUpdater(String updater) {
        this.updater = updater == null ? null : updater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_company_touch.update_time
     *
     * @return the value of c_company_touch.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_company_touch.update_time
     *
     * @param updateTime the value for c_company_touch.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_company_touch.custom1
     *
     * @return the value of c_company_touch.custom1
     *
     * @mbg.generated
     */
    public String getCustom1() {
        return custom1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_company_touch.custom1
     *
     * @param custom1 the value for c_company_touch.custom1
     *
     * @mbg.generated
     */
    public void setCustom1(String custom1) {
        this.custom1 = custom1 == null ? null : custom1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_company_touch.custom2
     *
     * @return the value of c_company_touch.custom2
     *
     * @mbg.generated
     */
    public String getCustom2() {
        return custom2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_company_touch.custom2
     *
     * @param custom2 the value for c_company_touch.custom2
     *
     * @mbg.generated
     */
    public void setCustom2(String custom2) {
        this.custom2 = custom2 == null ? null : custom2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_company_touch.custom3
     *
     * @return the value of c_company_touch.custom3
     *
     * @mbg.generated
     */
    public String getCustom3() {
        return custom3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_company_touch.custom3
     *
     * @param custom3 the value for c_company_touch.custom3
     *
     * @mbg.generated
     */
    public void setCustom3(String custom3) {
        this.custom3 = custom3 == null ? null : custom3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_company_touch.custom4
     *
     * @return the value of c_company_touch.custom4
     *
     * @mbg.generated
     */
    public String getCustom4() {
        return custom4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_company_touch.custom4
     *
     * @param custom4 the value for c_company_touch.custom4
     *
     * @mbg.generated
     */
    public void setCustom4(String custom4) {
        this.custom4 = custom4 == null ? null : custom4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_company_touch.choice1
     *
     * @return the value of c_company_touch.choice1
     *
     * @mbg.generated
     */
    public String getChoice1() {
        return choice1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_company_touch.choice1
     *
     * @param choice1 the value for c_company_touch.choice1
     *
     * @mbg.generated
     */
    public void setChoice1(String choice1) {
        this.choice1 = choice1 == null ? null : choice1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_company_touch.choice2
     *
     * @return the value of c_company_touch.choice2
     *
     * @mbg.generated
     */
    public String getChoice2() {
        return choice2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_company_touch.choice2
     *
     * @param choice2 the value for c_company_touch.choice2
     *
     * @mbg.generated
     */
    public void setChoice2(String choice2) {
        this.choice2 = choice2 == null ? null : choice2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_company_touch.choice3
     *
     * @return the value of c_company_touch.choice3
     *
     * @mbg.generated
     */
    public String getChoice3() {
        return choice3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_company_touch.choice3
     *
     * @param choice3 the value for c_company_touch.choice3
     *
     * @mbg.generated
     */
    public void setChoice3(String choice3) {
        this.choice3 = choice3 == null ? null : choice3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_company_touch.choice4
     *
     * @return the value of c_company_touch.choice4
     *
     * @mbg.generated
     */
    public String getChoice4() {
        return choice4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_company_touch.choice4
     *
     * @param choice4 the value for c_company_touch.choice4
     *
     * @mbg.generated
     */
    public void setChoice4(String choice4) {
        this.choice4 = choice4 == null ? null : choice4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_company_touch.time1
     *
     * @return the value of c_company_touch.time1
     *
     * @mbg.generated
     */
    public Date getTime1() {
        return time1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_company_touch.time1
     *
     * @param time1 the value for c_company_touch.time1
     *
     * @mbg.generated
     */
    public void setTime1(Date time1) {
        this.time1 = time1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_company_touch.time2
     *
     * @return the value of c_company_touch.time2
     *
     * @mbg.generated
     */
    public Date getTime2() {
        return time2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_company_touch.time2
     *
     * @param time2 the value for c_company_touch.time2
     *
     * @mbg.generated
     */
    public void setTime2(Date time2) {
        this.time2 = time2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_company_touch.m_type
     *
     * @return the value of c_company_touch.m_type
     *
     * @mbg.generated
     */
    public String getmType() {
        return mType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_company_touch.m_type
     *
     * @param mType the value for c_company_touch.m_type
     *
     * @mbg.generated
     */
    public void setmType(String mType) {
        this.mType = mType == null ? null : mType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_company_touch.share_flag
     *
     * @return the value of c_company_touch.share_flag
     *
     * @mbg.generated
     */
    public String getShareFlag() {
        return shareFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_company_touch.share_flag
     *
     * @param shareFlag the value for c_company_touch.share_flag
     *
     * @mbg.generated
     */
    public void setShareFlag(String shareFlag) {
        this.shareFlag = shareFlag == null ? null : shareFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_company_touch.owner_usr
     *
     * @return the value of c_company_touch.owner_usr
     *
     * @mbg.generated
     */
    public Integer getOwnerUsr() {
        return ownerUsr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_company_touch.owner_usr
     *
     * @param ownerUsr the value for c_company_touch.owner_usr
     *
     * @mbg.generated
     */
    public void setOwnerUsr(Integer ownerUsr) {
        this.ownerUsr = ownerUsr;
    }
}