package com.bean;

import lombok.Data;

@Data
public class DictionaryDetail {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_dictionary_detail.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_dictionary_detail.sort
     *
     * @mbg.generated
     */
    private Integer sort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_dictionary_detail.value
     *
     * @mbg.generated
     */
    private String value;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_dictionary_detail.sysFlag
     *
     * @mbg.generated
     */
    private String sysflag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_dictionary_detail.pid
     *
     * @mbg.generated
     */
    private Integer pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_dictionary_detail.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_dictionary_detail.value
     *
     * @param value the value for s_dictionary_detail.value
     *
     * @mbg.generated
     */
    public void setValue(String value) {
        this.value = value == null ? null : value.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_dictionary_detail.sysFlag
     *
     * @param sysflag the value for s_dictionary_detail.sysFlag
     *
     * @mbg.generated
     */
    public void setSysflag(String sysflag) {
        this.sysflag = sysflag == null ? null : sysflag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_dictionary_detail.remark
     *
     * @param remark the value for s_dictionary_detail.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}