package com.bean;

public class DictionaryClass {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_dictionary_class.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_dictionary_class.code
     *
     * @mbg.generated
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_dictionary_class.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_dictionary_class.chineseTableName
     *
     * @mbg.generated
     */
    private String chinesetablename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_dictionary_class.englishTableName
     *
     * @mbg.generated
     */
    private String englishtablename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_dictionary_class.available
     *
     * @mbg.generated
     */
    private String available;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_dictionary_class.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_dictionary_class.id
     *
     * @return the value of s_dictionary_class.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_dictionary_class.id
     *
     * @param id the value for s_dictionary_class.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_dictionary_class.code
     *
     * @return the value of s_dictionary_class.code
     *
     * @mbg.generated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_dictionary_class.code
     *
     * @param code the value for s_dictionary_class.code
     *
     * @mbg.generated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_dictionary_class.name
     *
     * @return the value of s_dictionary_class.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_dictionary_class.name
     *
     * @param name the value for s_dictionary_class.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_dictionary_class.chineseTableName
     *
     * @return the value of s_dictionary_class.chineseTableName
     *
     * @mbg.generated
     */
    public String getChinesetablename() {
        return chinesetablename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_dictionary_class.chineseTableName
     *
     * @param chinesetablename the value for s_dictionary_class.chineseTableName
     *
     * @mbg.generated
     */
    public void setChinesetablename(String chinesetablename) {
        this.chinesetablename = chinesetablename == null ? null : chinesetablename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_dictionary_class.englishTableName
     *
     * @return the value of s_dictionary_class.englishTableName
     *
     * @mbg.generated
     */
    public String getEnglishtablename() {
        return englishtablename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_dictionary_class.englishTableName
     *
     * @param englishtablename the value for s_dictionary_class.englishTableName
     *
     * @mbg.generated
     */
    public void setEnglishtablename(String englishtablename) {
        this.englishtablename = englishtablename == null ? null : englishtablename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_dictionary_class.available
     *
     * @return the value of s_dictionary_class.available
     *
     * @mbg.generated
     */
    public String getAvailable() {
        return available;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_dictionary_class.available
     *
     * @param available the value for s_dictionary_class.available
     *
     * @mbg.generated
     */
    public void setAvailable(String available) {
        this.available = available == null ? null : available.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_dictionary_class.remark
     *
     * @return the value of s_dictionary_class.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_dictionary_class.remark
     *
     * @param remark the value for s_dictionary_class.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}