package com.bean;

import java.util.Date;

public class Gather {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_gather.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_gather.owner_usr
     *
     * @mbg.generated
     */
    private Integer ownerUsr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_gather.creater
     *
     * @mbg.generated
     */
    private String creater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_gather.createTime
     *
     * @mbg.generated
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_gather.updater
     *
     * @mbg.generated
     */
    private String updater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_gather.updateTime
     *
     * @mbg.generated
     */
    private Date updatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_gather.c_id
     *
     * @mbg.generated
     */
    private Integer cId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_gather.c_name
     *
     * @mbg.generated
     */
    private String cName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_gather.c_type
     *
     * @mbg.generated
     */
    private String cType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_gather.payer
     *
     * @mbg.generated
     */
    private String payer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_gather.pay_date
     *
     * @mbg.generated
     */
    private Date payDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_gather.pay_type
     *
     * @mbg.generated
     */
    private String payType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_gather.bill_code
     *
     * @mbg.generated
     */
    private String billCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_gather.handler
     *
     * @mbg.generated
     */
    private String handler;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_gather.total
     *
     * @mbg.generated
     */
    private Double total;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_gather.statusid
     *
     * @mbg.generated
     */
    private String statusid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_gather.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_gather.auditor
     *
     * @mbg.generated
     */
    private String auditor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_gather.audit_date
     *
     * @mbg.generated
     */
    private Date auditDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_gather.code
     *
     * @mbg.generated
     */
    private String code;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_gather.id
     *
     * @return the value of b_gather.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_gather.id
     *
     * @param id the value for b_gather.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_gather.owner_usr
     *
     * @return the value of b_gather.owner_usr
     *
     * @mbg.generated
     */
    public Integer getOwnerUsr() {
        return ownerUsr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_gather.owner_usr
     *
     * @param ownerUsr the value for b_gather.owner_usr
     *
     * @mbg.generated
     */
    public void setOwnerUsr(Integer ownerUsr) {
        this.ownerUsr = ownerUsr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_gather.creater
     *
     * @return the value of b_gather.creater
     *
     * @mbg.generated
     */
    public String getCreater() {
        return creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_gather.creater
     *
     * @param creater the value for b_gather.creater
     *
     * @mbg.generated
     */
    public void setCreater(String creater) {
        this.creater = creater == null ? null : creater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_gather.createTime
     *
     * @return the value of b_gather.createTime
     *
     * @mbg.generated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_gather.createTime
     *
     * @param createtime the value for b_gather.createTime
     *
     * @mbg.generated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_gather.updater
     *
     * @return the value of b_gather.updater
     *
     * @mbg.generated
     */
    public String getUpdater() {
        return updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_gather.updater
     *
     * @param updater the value for b_gather.updater
     *
     * @mbg.generated
     */
    public void setUpdater(String updater) {
        this.updater = updater == null ? null : updater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_gather.updateTime
     *
     * @return the value of b_gather.updateTime
     *
     * @mbg.generated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_gather.updateTime
     *
     * @param updatetime the value for b_gather.updateTime
     *
     * @mbg.generated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_gather.c_id
     *
     * @return the value of b_gather.c_id
     *
     * @mbg.generated
     */
    public Integer getcId() {
        return cId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_gather.c_id
     *
     * @param cId the value for b_gather.c_id
     *
     * @mbg.generated
     */
    public void setcId(Integer cId) {
        this.cId = cId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_gather.c_name
     *
     * @return the value of b_gather.c_name
     *
     * @mbg.generated
     */
    public String getcName() {
        return cName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_gather.c_name
     *
     * @param cName the value for b_gather.c_name
     *
     * @mbg.generated
     */
    public void setcName(String cName) {
        this.cName = cName == null ? null : cName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_gather.c_type
     *
     * @return the value of b_gather.c_type
     *
     * @mbg.generated
     */
    public String getcType() {
        return cType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_gather.c_type
     *
     * @param cType the value for b_gather.c_type
     *
     * @mbg.generated
     */
    public void setcType(String cType) {
        this.cType = cType == null ? null : cType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_gather.payer
     *
     * @return the value of b_gather.payer
     *
     * @mbg.generated
     */
    public String getPayer() {
        return payer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_gather.payer
     *
     * @param payer the value for b_gather.payer
     *
     * @mbg.generated
     */
    public void setPayer(String payer) {
        this.payer = payer == null ? null : payer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_gather.pay_date
     *
     * @return the value of b_gather.pay_date
     *
     * @mbg.generated
     */
    public Date getPayDate() {
        return payDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_gather.pay_date
     *
     * @param payDate the value for b_gather.pay_date
     *
     * @mbg.generated
     */
    public void setPayDate(Date payDate) {
        this.payDate = payDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_gather.pay_type
     *
     * @return the value of b_gather.pay_type
     *
     * @mbg.generated
     */
    public String getPayType() {
        return payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_gather.pay_type
     *
     * @param payType the value for b_gather.pay_type
     *
     * @mbg.generated
     */
    public void setPayType(String payType) {
        this.payType = payType == null ? null : payType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_gather.bill_code
     *
     * @return the value of b_gather.bill_code
     *
     * @mbg.generated
     */
    public String getBillCode() {
        return billCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_gather.bill_code
     *
     * @param billCode the value for b_gather.bill_code
     *
     * @mbg.generated
     */
    public void setBillCode(String billCode) {
        this.billCode = billCode == null ? null : billCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_gather.handler
     *
     * @return the value of b_gather.handler
     *
     * @mbg.generated
     */
    public String getHandler() {
        return handler;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_gather.handler
     *
     * @param handler the value for b_gather.handler
     *
     * @mbg.generated
     */
    public void setHandler(String handler) {
        this.handler = handler == null ? null : handler.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_gather.total
     *
     * @return the value of b_gather.total
     *
     * @mbg.generated
     */
    public Double getTotal() {
        return total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_gather.total
     *
     * @param total the value for b_gather.total
     *
     * @mbg.generated
     */
    public void setTotal(Double total) {
        this.total = total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_gather.statusid
     *
     * @return the value of b_gather.statusid
     *
     * @mbg.generated
     */
    public String getStatusid() {
        return statusid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_gather.statusid
     *
     * @param statusid the value for b_gather.statusid
     *
     * @mbg.generated
     */
    public void setStatusid(String statusid) {
        this.statusid = statusid == null ? null : statusid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_gather.status
     *
     * @return the value of b_gather.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_gather.status
     *
     * @param status the value for b_gather.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_gather.auditor
     *
     * @return the value of b_gather.auditor
     *
     * @mbg.generated
     */
    public String getAuditor() {
        return auditor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_gather.auditor
     *
     * @param auditor the value for b_gather.auditor
     *
     * @mbg.generated
     */
    public void setAuditor(String auditor) {
        this.auditor = auditor == null ? null : auditor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_gather.audit_date
     *
     * @return the value of b_gather.audit_date
     *
     * @mbg.generated
     */
    public Date getAuditDate() {
        return auditDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_gather.audit_date
     *
     * @param auditDate the value for b_gather.audit_date
     *
     * @mbg.generated
     */
    public void setAuditDate(Date auditDate) {
        this.auditDate = auditDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_gather.code
     *
     * @return the value of b_gather.code
     *
     * @mbg.generated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_gather.code
     *
     * @param code the value for b_gather.code
     *
     * @mbg.generated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }
}