package com.bean;

import lombok.Data;

import java.util.Date;

/**
 * @version 2017/6/29.
 * @auther CrazyBunQnQ
 */
@Data
public class Gather {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_gather.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_gather.owner_usr
     *
     * @mbg.generated
     */
    private Integer ownerUsr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_gather.creater
     *
     * @mbg.generated
     */
    private String creater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_gather.createTime
     *
     * @mbg.generated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_gather.updater
     *
     * @mbg.generated
     */
    private String updater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_gather.updateTime
     *
     * @mbg.generated
     */
    private Date updatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_gather.c_id
     *
     * @mbg.generated
     */
    private Integer cId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_gather.c_name
     *
     * @mbg.generated
     */
    private String cName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_gather.c_type
     *
     * @mbg.generated
     */
    private String cType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_gather.payer
     *
     * @mbg.generated
     */
    private String payer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_gather.pay_date
     *
     * @mbg.generated
     */
    private Date payDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_gather.pay_type
     *
     * @mbg.generated
     */
    private String payType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_gather.bill_code
     *
     * @mbg.generated
     */
    private String billCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_gather.handler
     *
     * @mbg.generated
     */
    private String handler;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_gather.total
     *
     * @mbg.generated
     */
    private Double total;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_gather.statusid
     *
     * @mbg.generated
     */
    private String statusid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_gather.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_gather.auditor
     *
     * @mbg.generated
     */
    private String auditor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_gather.audit_date
     *
     * @mbg.generated
     */
    private Date auditDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_gather.code
     *
     * @mbg.generated
     */
    private String code;

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_gather.creater
     *
     * @param creater the value for b_gather.creater
     *
     * @mbg.generated
     */
    public void setCreater(String creater) {
        this.creater = creater == null ? null : creater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_gather.updater
     *
     * @param updater the value for b_gather.updater
     *
     * @mbg.generated
     */
    public void setUpdater(String updater) {
        this.updater = updater == null ? null : updater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_gather.c_name
     *
     * @param cName the value for b_gather.c_name
     *
     * @mbg.generated
     */
    public void setcName(String cName) {
        this.cName = cName == null ? null : cName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_gather.c_type
     *
     * @param cType the value for b_gather.c_type
     *
     * @mbg.generated
     */
    public void setcType(String cType) {
        this.cType = cType == null ? null : cType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_gather.payer
     *
     * @param payer the value for b_gather.payer
     *
     * @mbg.generated
     */
    public void setPayer(String payer) {
        this.payer = payer == null ? null : payer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_gather.pay_type
     *
     * @param payType the value for b_gather.pay_type
     *
     * @mbg.generated
     */
    public void setPayType(String payType) {
        this.payType = payType == null ? null : payType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_gather.bill_code
     *
     * @param billCode the value for b_gather.bill_code
     *
     * @mbg.generated
     */
    public void setBillCode(String billCode) {
        this.billCode = billCode == null ? null : billCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_gather.handler
     *
     * @param handler the value for b_gather.handler
     *
     * @mbg.generated
     */
    public void setHandler(String handler) {
        this.handler = handler == null ? null : handler.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_gather.statusid
     *
     * @param statusid the value for b_gather.statusid
     *
     * @mbg.generated
     */
    public void setStatusid(String statusid) {
        this.statusid = statusid == null ? null : statusid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_gather.status
     *
     * @param status the value for b_gather.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_gather.auditor
     *
     * @param auditor the value for b_gather.auditor
     *
     * @mbg.generated
     */
    public void setAuditor(String auditor) {
        this.auditor = auditor == null ? null : auditor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_gather.code
     *
     * @param code the value for b_gather.code
     *
     * @mbg.generated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }
}