package com.bean;

public class GatherWithBLOBs extends Gather {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_gather.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_gather.audit_idea
     *
     * @mbg.generated
     */
    private String auditIdea;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_gather.remark
     *
     * @return the value of b_gather.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_gather.remark
     *
     * @param remark the value for b_gather.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_gather.audit_idea
     *
     * @return the value of b_gather.audit_idea
     *
     * @mbg.generated
     */
    public String getAuditIdea() {
        return auditIdea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_gather.audit_idea
     *
     * @param auditIdea the value for b_gather.audit_idea
     *
     * @mbg.generated
     */
    public void setAuditIdea(String auditIdea) {
        this.auditIdea = auditIdea == null ? null : auditIdea.trim();
    }
}