package com.bean;

import lombok.Data;

@Data
public class NeedGatherWithBLOBs extends NeedGather {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_need_gather.shareId
     *
     * @mbg.generated
     */
    private String shareid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_need_gather.read_shareId
     *
     * @mbg.generated
     */
    private String readShareid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_need_gather.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_need_gather.shareId
     *
     * @param shareid the value for b_need_gather.shareId
     *
     * @mbg.generated
     */
    public void setShareid(String shareid) {
        this.shareid = shareid == null ? null : shareid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_need_gather.read_shareId
     *
     * @param readShareid the value for b_need_gather.read_shareId
     *
     * @mbg.generated
     */
    public void setReadShareid(String readShareid) {
        this.readShareid = readShareid == null ? null : readShareid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_need_gather.remark
     *
     * @param remark the value for b_need_gather.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}