package com.bean;

public class OrderDetail {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_order_detail.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_order_detail.p_name
     *
     * @mbg.generated
     */
    private String pName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_order_detail.spec
     *
     * @mbg.generated
     */
    private String spec;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_order_detail.unit
     *
     * @mbg.generated
     */
    private String unit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_order_detail.amount
     *
     * @mbg.generated
     */
    private Double amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_order_detail.price
     *
     * @mbg.generated
     */
    private Double price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_order_detail.agio
     *
     * @mbg.generated
     */
    private Double agio;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_order_detail.total
     *
     * @mbg.generated
     */
    private Double total;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_order_detail.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_order_detail.order_id
     *
     * @mbg.generated
     */
    private Integer orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_order_detail.p_id
     *
     * @mbg.generated
     */
    private Integer pId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_order_detail.id
     *
     * @return the value of b_order_detail.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_order_detail.id
     *
     * @param id the value for b_order_detail.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_order_detail.p_name
     *
     * @return the value of b_order_detail.p_name
     *
     * @mbg.generated
     */
    public String getpName() {
        return pName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_order_detail.p_name
     *
     * @param pName the value for b_order_detail.p_name
     *
     * @mbg.generated
     */
    public void setpName(String pName) {
        this.pName = pName == null ? null : pName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_order_detail.spec
     *
     * @return the value of b_order_detail.spec
     *
     * @mbg.generated
     */
    public String getSpec() {
        return spec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_order_detail.spec
     *
     * @param spec the value for b_order_detail.spec
     *
     * @mbg.generated
     */
    public void setSpec(String spec) {
        this.spec = spec == null ? null : spec.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_order_detail.unit
     *
     * @return the value of b_order_detail.unit
     *
     * @mbg.generated
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_order_detail.unit
     *
     * @param unit the value for b_order_detail.unit
     *
     * @mbg.generated
     */
    public void setUnit(String unit) {
        this.unit = unit == null ? null : unit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_order_detail.amount
     *
     * @return the value of b_order_detail.amount
     *
     * @mbg.generated
     */
    public Double getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_order_detail.amount
     *
     * @param amount the value for b_order_detail.amount
     *
     * @mbg.generated
     */
    public void setAmount(Double amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_order_detail.price
     *
     * @return the value of b_order_detail.price
     *
     * @mbg.generated
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_order_detail.price
     *
     * @param price the value for b_order_detail.price
     *
     * @mbg.generated
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_order_detail.agio
     *
     * @return the value of b_order_detail.agio
     *
     * @mbg.generated
     */
    public Double getAgio() {
        return agio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_order_detail.agio
     *
     * @param agio the value for b_order_detail.agio
     *
     * @mbg.generated
     */
    public void setAgio(Double agio) {
        this.agio = agio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_order_detail.total
     *
     * @return the value of b_order_detail.total
     *
     * @mbg.generated
     */
    public Double getTotal() {
        return total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_order_detail.total
     *
     * @param total the value for b_order_detail.total
     *
     * @mbg.generated
     */
    public void setTotal(Double total) {
        this.total = total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_order_detail.remark
     *
     * @return the value of b_order_detail.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_order_detail.remark
     *
     * @param remark the value for b_order_detail.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_order_detail.order_id
     *
     * @return the value of b_order_detail.order_id
     *
     * @mbg.generated
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_order_detail.order_id
     *
     * @param orderId the value for b_order_detail.order_id
     *
     * @mbg.generated
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_order_detail.p_id
     *
     * @return the value of b_order_detail.p_id
     *
     * @mbg.generated
     */
    public Integer getpId() {
        return pId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_order_detail.p_id
     *
     * @param pId the value for b_order_detail.p_id
     *
     * @mbg.generated
     */
    public void setpId(Integer pId) {
        this.pId = pId;
    }
}