package com.bean;

import lombok.Data;

/**
 * @version 2017/6/29.
 * @auther CrazyBunQnQ
 */
@Data
public class OrderWithBLOBs extends Order {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_order.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_order.audit_reason
     *
     * @mbg.generated
     */
    private String auditReason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_order.share_ids
     *
     * @mbg.generated
     */
    private String shareIds;

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_order.remark
     *
     * @param remark the value for b_order.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_order.audit_reason
     *
     * @param auditReason the value for b_order.audit_reason
     *
     * @mbg.generated
     */
    public void setAuditReason(String auditReason) {
        this.auditReason = auditReason == null ? null : auditReason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_order.share_ids
     *
     * @param shareIds the value for b_order.share_ids
     *
     * @mbg.generated
     */
    public void setShareIds(String shareIds) {
        this.shareIds = shareIds == null ? null : shareIds.trim();
    }
}