package com.bean;

import lombok.Data;

import java.util.Date;

@Data
public class Product {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_product.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_product.ptype_id
     *
     * @mbg.generated
     */
    private Integer ptypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_product.sort
     *
     * @mbg.generated
     */
    private Integer sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_product.creater
     *
     * @mbg.generated
     */
    private String creater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_product.createTime
     *
     * @mbg.generated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_product.updater
     *
     * @mbg.generated
     */
    private String updater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_product.updateTime
     *
     * @mbg.generated
     */
    private Date updatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_product.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_product.code
     *
     * @mbg.generated
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_product.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_product.model
     *
     * @mbg.generated
     */
    private String model;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_product.spec
     *
     * @mbg.generated
     */
    private String spec;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_product.unit
     *
     * @mbg.generated
     */
    private String unit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_product.color
     *
     * @mbg.generated
     */
    private String color;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_product.product_size
     *
     * @mbg.generated
     */
    private String productSize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_product.bar_code
     *
     * @mbg.generated
     */
    private String barCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_product.provider
     *
     * @mbg.generated
     */
    private String provider;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_product.stock
     *
     * @mbg.generated
     */
    private Double stock;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_product.price
     *
     * @mbg.generated
     */
    private Double price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_product.buy_price
     *
     * @mbg.generated
     */
    private Double buyPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_product.picture
     *
     * @mbg.generated
     */
    private String picture;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_product.pycode
     *
     * @mbg.generated
     */
    private String pycode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_product.custom1
     *
     * @mbg.generated
     */
    private String custom1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_product.custom2
     *
     * @mbg.generated
     */
    private String custom2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_product.custom3
     *
     * @mbg.generated
     */
    private String custom3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_product.custom4
     *
     * @mbg.generated
     */
    private String custom4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_product.choice1
     *
     * @mbg.generated
     */
    private String choice1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_product.choice2
     *
     * @mbg.generated
     */
    private String choice2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_product.choice3
     *
     * @mbg.generated
     */
    private String choice3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_product.choice4
     *
     * @mbg.generated
     */
    private String choice4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_product.time1
     *
     * @mbg.generated
     */
    private Date time1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_product.time2
     *
     * @mbg.generated
     */
    private Date time2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_product.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_product.creater
     *
     * @param creater the value for b_product.creater
     *
     * @mbg.generated
     */
    public void setCreater(String creater) {
        this.creater = creater == null ? null : creater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_product.updater
     *
     * @param updater the value for b_product.updater
     *
     * @mbg.generated
     */
    public void setUpdater(String updater) {
        this.updater = updater == null ? null : updater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_product.status
     *
     * @param status the value for b_product.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_product.code
     *
     * @param code the value for b_product.code
     *
     * @mbg.generated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_product.name
     *
     * @param name the value for b_product.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_product.model
     *
     * @param model the value for b_product.model
     *
     * @mbg.generated
     */
    public void setModel(String model) {
        this.model = model == null ? null : model.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_product.spec
     *
     * @param spec the value for b_product.spec
     *
     * @mbg.generated
     */
    public void setSpec(String spec) {
        this.spec = spec == null ? null : spec.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_product.unit
     *
     * @param unit the value for b_product.unit
     *
     * @mbg.generated
     */
    public void setUnit(String unit) {
        this.unit = unit == null ? null : unit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_product.color
     *
     * @param color the value for b_product.color
     *
     * @mbg.generated
     */
    public void setColor(String color) {
        this.color = color == null ? null : color.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_product.product_size
     *
     * @param productSize the value for b_product.product_size
     *
     * @mbg.generated
     */
    public void setProductSize(String productSize) {
        this.productSize = productSize == null ? null : productSize.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_product.bar_code
     *
     * @param barCode the value for b_product.bar_code
     *
     * @mbg.generated
     */
    public void setBarCode(String barCode) {
        this.barCode = barCode == null ? null : barCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_product.provider
     *
     * @param provider the value for b_product.provider
     *
     * @mbg.generated
     */
    public void setProvider(String provider) {
        this.provider = provider == null ? null : provider.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_product.picture
     *
     * @param picture the value for b_product.picture
     *
     * @mbg.generated
     */
    public void setPicture(String picture) {
        this.picture = picture == null ? null : picture.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_product.pycode
     *
     * @param pycode the value for b_product.pycode
     *
     * @mbg.generated
     */
    public void setPycode(String pycode) {
        this.pycode = pycode == null ? null : pycode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_product.custom1
     *
     * @param custom1 the value for b_product.custom1
     *
     * @mbg.generated
     */
    public void setCustom1(String custom1) {
        this.custom1 = custom1 == null ? null : custom1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_product.custom2
     *
     * @param custom2 the value for b_product.custom2
     *
     * @mbg.generated
     */
    public void setCustom2(String custom2) {
        this.custom2 = custom2 == null ? null : custom2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_product.custom3
     *
     * @param custom3 the value for b_product.custom3
     *
     * @mbg.generated
     */
    public void setCustom3(String custom3) {
        this.custom3 = custom3 == null ? null : custom3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_product.custom4
     *
     * @param custom4 the value for b_product.custom4
     *
     * @mbg.generated
     */
    public void setCustom4(String custom4) {
        this.custom4 = custom4 == null ? null : custom4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_product.choice1
     *
     * @param choice1 the value for b_product.choice1
     *
     * @mbg.generated
     */
    public void setChoice1(String choice1) {
        this.choice1 = choice1 == null ? null : choice1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_product.choice2
     *
     * @param choice2 the value for b_product.choice2
     *
     * @mbg.generated
     */
    public void setChoice2(String choice2) {
        this.choice2 = choice2 == null ? null : choice2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_product.choice3
     *
     * @param choice3 the value for b_product.choice3
     *
     * @mbg.generated
     */
    public void setChoice3(String choice3) {
        this.choice3 = choice3 == null ? null : choice3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_product.choice4
     *
     * @param choice4 the value for b_product.choice4
     *
     * @mbg.generated
     */
    public void setChoice4(String choice4) {
        this.choice4 = choice4 == null ? null : choice4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_product.remark
     *
     * @param remark the value for b_product.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}