package com.bean;

import lombok.Data;

@Data
public class Province {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_province.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_province.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_province.pycode
     *
     * @mbg.generated
     */
    private String pycode;

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_province.name
     *
     * @param name the value for s_province.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_province.pycode
     *
     * @param pycode the value for s_province.pycode
     *
     * @mbg.generated
     */
    public void setPycode(String pycode) {
        this.pycode = pycode == null ? null : pycode.trim();
    }
}