package com.bean;

import java.util.Date;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user.creator
     *
     * @mbg.generated
     */
    private String creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user.createTime
     *
     * @mbg.generated
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user.updater
     *
     * @mbg.generated
     */
    private String updater;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user.updateTime
     *
     * @mbg.generated
     */
    private Date updatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user.cnname
     *
     * @mbg.generated
     */
    private String cnname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user.password
     *
     * @mbg.generated
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user.address
     *
     * @mbg.generated
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user.telephone
     *
     * @mbg.generated
     */
    private String telephone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user.email
     *
     * @mbg.generated
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user.beginDate
     *
     * @mbg.generated
     */
    private Date begindate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user.endDate
     *
     * @mbg.generated
     */
    private Date enddate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user.access_fileLevel
     *
     * @mbg.generated
     */
    private String accessFilelevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user.commendman
     *
     * @mbg.generated
     */
    private String commendman;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user.movetelephone
     *
     * @mbg.generated
     */
    private String movetelephone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user.nowaddress
     *
     * @mbg.generated
     */
    private String nowaddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user.nowtelephone
     *
     * @mbg.generated
     */
    private String nowtelephone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user.identitycode
     *
     * @mbg.generated
     */
    private String identitycode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user.insurancecode
     *
     * @mbg.generated
     */
    private String insurancecode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user.instancylinkman
     *
     * @mbg.generated
     */
    private String instancylinkman;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user.instancytelephone
     *
     * @mbg.generated
     */
    private String instancytelephone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user.sex
     *
     * @mbg.generated
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user.birthday
     *
     * @mbg.generated
     */
    private Date birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user.personneltype
     *
     * @mbg.generated
     */
    private String personneltype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user.duty
     *
     * @mbg.generated
     */
    private String duty;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user.workdate
     *
     * @mbg.generated
     */
    private Date workdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user.highschool
     *
     * @mbg.generated
     */
    private String highschool;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user.finishschool
     *
     * @mbg.generated
     */
    private String finishschool;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user.finishschooldate
     *
     * @mbg.generated
     */
    private Date finishschooldate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user.consortname
     *
     * @mbg.generated
     */
    private String consortname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user.youngonename
     *
     * @mbg.generated
     */
    private String youngonename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user.officetelephone
     *
     * @mbg.generated
     */
    private String officetelephone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user.consorttelephone
     *
     * @mbg.generated
     */
    private String consorttelephone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user.consortcompany
     *
     * @mbg.generated
     */
    private String consortcompany;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user.role_id
     *
     * @mbg.generated
     */
    private Integer roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user.group_Id
     *
     * @mbg.generated
     */
    private Integer groupId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user.access_group_id
     *
     * @mbg.generated
     */
    private Integer accessGroupId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user.id
     *
     * @return the value of s_user.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user.id
     *
     * @param id the value for s_user.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user.creator
     *
     * @return the value of s_user.creator
     *
     * @mbg.generated
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user.creator
     *
     * @param creator the value for s_user.creator
     *
     * @mbg.generated
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user.createTime
     *
     * @return the value of s_user.createTime
     *
     * @mbg.generated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user.createTime
     *
     * @param createtime the value for s_user.createTime
     *
     * @mbg.generated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user.updater
     *
     * @return the value of s_user.updater
     *
     * @mbg.generated
     */
    public String getUpdater() {
        return updater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user.updater
     *
     * @param updater the value for s_user.updater
     *
     * @mbg.generated
     */
    public void setUpdater(String updater) {
        this.updater = updater == null ? null : updater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user.updateTime
     *
     * @return the value of s_user.updateTime
     *
     * @mbg.generated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user.updateTime
     *
     * @param updatetime the value for s_user.updateTime
     *
     * @mbg.generated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user.name
     *
     * @return the value of s_user.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user.name
     *
     * @param name the value for s_user.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user.cnname
     *
     * @return the value of s_user.cnname
     *
     * @mbg.generated
     */
    public String getCnname() {
        return cnname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user.cnname
     *
     * @param cnname the value for s_user.cnname
     *
     * @mbg.generated
     */
    public void setCnname(String cnname) {
        this.cnname = cnname == null ? null : cnname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user.password
     *
     * @return the value of s_user.password
     *
     * @mbg.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user.password
     *
     * @param password the value for s_user.password
     *
     * @mbg.generated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user.address
     *
     * @return the value of s_user.address
     *
     * @mbg.generated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user.address
     *
     * @param address the value for s_user.address
     *
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user.telephone
     *
     * @return the value of s_user.telephone
     *
     * @mbg.generated
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user.telephone
     *
     * @param telephone the value for s_user.telephone
     *
     * @mbg.generated
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone == null ? null : telephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user.email
     *
     * @return the value of s_user.email
     *
     * @mbg.generated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user.email
     *
     * @param email the value for s_user.email
     *
     * @mbg.generated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user.beginDate
     *
     * @return the value of s_user.beginDate
     *
     * @mbg.generated
     */
    public Date getBegindate() {
        return begindate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user.beginDate
     *
     * @param begindate the value for s_user.beginDate
     *
     * @mbg.generated
     */
    public void setBegindate(Date begindate) {
        this.begindate = begindate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user.endDate
     *
     * @return the value of s_user.endDate
     *
     * @mbg.generated
     */
    public Date getEnddate() {
        return enddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user.endDate
     *
     * @param enddate the value for s_user.endDate
     *
     * @mbg.generated
     */
    public void setEnddate(Date enddate) {
        this.enddate = enddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user.access_fileLevel
     *
     * @return the value of s_user.access_fileLevel
     *
     * @mbg.generated
     */
    public String getAccessFilelevel() {
        return accessFilelevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user.access_fileLevel
     *
     * @param accessFilelevel the value for s_user.access_fileLevel
     *
     * @mbg.generated
     */
    public void setAccessFilelevel(String accessFilelevel) {
        this.accessFilelevel = accessFilelevel == null ? null : accessFilelevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user.status
     *
     * @return the value of s_user.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user.status
     *
     * @param status the value for s_user.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user.commendman
     *
     * @return the value of s_user.commendman
     *
     * @mbg.generated
     */
    public String getCommendman() {
        return commendman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user.commendman
     *
     * @param commendman the value for s_user.commendman
     *
     * @mbg.generated
     */
    public void setCommendman(String commendman) {
        this.commendman = commendman == null ? null : commendman.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user.movetelephone
     *
     * @return the value of s_user.movetelephone
     *
     * @mbg.generated
     */
    public String getMovetelephone() {
        return movetelephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user.movetelephone
     *
     * @param movetelephone the value for s_user.movetelephone
     *
     * @mbg.generated
     */
    public void setMovetelephone(String movetelephone) {
        this.movetelephone = movetelephone == null ? null : movetelephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user.nowaddress
     *
     * @return the value of s_user.nowaddress
     *
     * @mbg.generated
     */
    public String getNowaddress() {
        return nowaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user.nowaddress
     *
     * @param nowaddress the value for s_user.nowaddress
     *
     * @mbg.generated
     */
    public void setNowaddress(String nowaddress) {
        this.nowaddress = nowaddress == null ? null : nowaddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user.nowtelephone
     *
     * @return the value of s_user.nowtelephone
     *
     * @mbg.generated
     */
    public String getNowtelephone() {
        return nowtelephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user.nowtelephone
     *
     * @param nowtelephone the value for s_user.nowtelephone
     *
     * @mbg.generated
     */
    public void setNowtelephone(String nowtelephone) {
        this.nowtelephone = nowtelephone == null ? null : nowtelephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user.identitycode
     *
     * @return the value of s_user.identitycode
     *
     * @mbg.generated
     */
    public String getIdentitycode() {
        return identitycode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user.identitycode
     *
     * @param identitycode the value for s_user.identitycode
     *
     * @mbg.generated
     */
    public void setIdentitycode(String identitycode) {
        this.identitycode = identitycode == null ? null : identitycode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user.insurancecode
     *
     * @return the value of s_user.insurancecode
     *
     * @mbg.generated
     */
    public String getInsurancecode() {
        return insurancecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user.insurancecode
     *
     * @param insurancecode the value for s_user.insurancecode
     *
     * @mbg.generated
     */
    public void setInsurancecode(String insurancecode) {
        this.insurancecode = insurancecode == null ? null : insurancecode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user.instancylinkman
     *
     * @return the value of s_user.instancylinkman
     *
     * @mbg.generated
     */
    public String getInstancylinkman() {
        return instancylinkman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user.instancylinkman
     *
     * @param instancylinkman the value for s_user.instancylinkman
     *
     * @mbg.generated
     */
    public void setInstancylinkman(String instancylinkman) {
        this.instancylinkman = instancylinkman == null ? null : instancylinkman.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user.instancytelephone
     *
     * @return the value of s_user.instancytelephone
     *
     * @mbg.generated
     */
    public String getInstancytelephone() {
        return instancytelephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user.instancytelephone
     *
     * @param instancytelephone the value for s_user.instancytelephone
     *
     * @mbg.generated
     */
    public void setInstancytelephone(String instancytelephone) {
        this.instancytelephone = instancytelephone == null ? null : instancytelephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user.sex
     *
     * @return the value of s_user.sex
     *
     * @mbg.generated
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user.sex
     *
     * @param sex the value for s_user.sex
     *
     * @mbg.generated
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user.birthday
     *
     * @return the value of s_user.birthday
     *
     * @mbg.generated
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user.birthday
     *
     * @param birthday the value for s_user.birthday
     *
     * @mbg.generated
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user.personneltype
     *
     * @return the value of s_user.personneltype
     *
     * @mbg.generated
     */
    public String getPersonneltype() {
        return personneltype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user.personneltype
     *
     * @param personneltype the value for s_user.personneltype
     *
     * @mbg.generated
     */
    public void setPersonneltype(String personneltype) {
        this.personneltype = personneltype == null ? null : personneltype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user.duty
     *
     * @return the value of s_user.duty
     *
     * @mbg.generated
     */
    public String getDuty() {
        return duty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user.duty
     *
     * @param duty the value for s_user.duty
     *
     * @mbg.generated
     */
    public void setDuty(String duty) {
        this.duty = duty == null ? null : duty.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user.workdate
     *
     * @return the value of s_user.workdate
     *
     * @mbg.generated
     */
    public Date getWorkdate() {
        return workdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user.workdate
     *
     * @param workdate the value for s_user.workdate
     *
     * @mbg.generated
     */
    public void setWorkdate(Date workdate) {
        this.workdate = workdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user.highschool
     *
     * @return the value of s_user.highschool
     *
     * @mbg.generated
     */
    public String getHighschool() {
        return highschool;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user.highschool
     *
     * @param highschool the value for s_user.highschool
     *
     * @mbg.generated
     */
    public void setHighschool(String highschool) {
        this.highschool = highschool == null ? null : highschool.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user.finishschool
     *
     * @return the value of s_user.finishschool
     *
     * @mbg.generated
     */
    public String getFinishschool() {
        return finishschool;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user.finishschool
     *
     * @param finishschool the value for s_user.finishschool
     *
     * @mbg.generated
     */
    public void setFinishschool(String finishschool) {
        this.finishschool = finishschool == null ? null : finishschool.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user.finishschooldate
     *
     * @return the value of s_user.finishschooldate
     *
     * @mbg.generated
     */
    public Date getFinishschooldate() {
        return finishschooldate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user.finishschooldate
     *
     * @param finishschooldate the value for s_user.finishschooldate
     *
     * @mbg.generated
     */
    public void setFinishschooldate(Date finishschooldate) {
        this.finishschooldate = finishschooldate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user.consortname
     *
     * @return the value of s_user.consortname
     *
     * @mbg.generated
     */
    public String getConsortname() {
        return consortname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user.consortname
     *
     * @param consortname the value for s_user.consortname
     *
     * @mbg.generated
     */
    public void setConsortname(String consortname) {
        this.consortname = consortname == null ? null : consortname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user.youngonename
     *
     * @return the value of s_user.youngonename
     *
     * @mbg.generated
     */
    public String getYoungonename() {
        return youngonename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user.youngonename
     *
     * @param youngonename the value for s_user.youngonename
     *
     * @mbg.generated
     */
    public void setYoungonename(String youngonename) {
        this.youngonename = youngonename == null ? null : youngonename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user.officetelephone
     *
     * @return the value of s_user.officetelephone
     *
     * @mbg.generated
     */
    public String getOfficetelephone() {
        return officetelephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user.officetelephone
     *
     * @param officetelephone the value for s_user.officetelephone
     *
     * @mbg.generated
     */
    public void setOfficetelephone(String officetelephone) {
        this.officetelephone = officetelephone == null ? null : officetelephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user.consorttelephone
     *
     * @return the value of s_user.consorttelephone
     *
     * @mbg.generated
     */
    public String getConsorttelephone() {
        return consorttelephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user.consorttelephone
     *
     * @param consorttelephone the value for s_user.consorttelephone
     *
     * @mbg.generated
     */
    public void setConsorttelephone(String consorttelephone) {
        this.consorttelephone = consorttelephone == null ? null : consorttelephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user.consortcompany
     *
     * @return the value of s_user.consortcompany
     *
     * @mbg.generated
     */
    public String getConsortcompany() {
        return consortcompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user.consortcompany
     *
     * @param consortcompany the value for s_user.consortcompany
     *
     * @mbg.generated
     */
    public void setConsortcompany(String consortcompany) {
        this.consortcompany = consortcompany == null ? null : consortcompany.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user.role_id
     *
     * @return the value of s_user.role_id
     *
     * @mbg.generated
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user.role_id
     *
     * @param roleId the value for s_user.role_id
     *
     * @mbg.generated
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user.group_Id
     *
     * @return the value of s_user.group_Id
     *
     * @mbg.generated
     */
    public Integer getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user.group_Id
     *
     * @param groupId the value for s_user.group_Id
     *
     * @mbg.generated
     */
    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user.access_group_id
     *
     * @return the value of s_user.access_group_id
     *
     * @mbg.generated
     */
    public Integer getAccessGroupId() {
        return accessGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user.access_group_id
     *
     * @param accessGroupId the value for s_user.access_group_id
     *
     * @mbg.generated
     */
    public void setAccessGroupId(Integer accessGroupId) {
        this.accessGroupId = accessGroupId;
    }
}