package com.bean;

public class UserWithBLOBs extends User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user.menus
     *
     * @mbg.generated
     */
    private String menus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user.popedom
     *
     * @mbg.generated
     */
    private String popedom;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user.avocation
     *
     * @mbg.generated
     */
    private String avocation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user.strongsuit
     *
     * @mbg.generated
     */
    private String strongsuit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user.communicate
     *
     * @mbg.generated
     */
    private String communicate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user.bringup
     *
     * @mbg.generated
     */
    private String bringup;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user.organise
     *
     * @mbg.generated
     */
    private String organise;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user.analyse
     *
     * @mbg.generated
     */
    private String analyse;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user.planing
     *
     * @mbg.generated
     */
    private String planing;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user.empolder
     *
     * @mbg.generated
     */
    private String empolder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user.relation
     *
     * @mbg.generated
     */
    private String relation;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user.remark
     *
     * @return the value of s_user.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user.remark
     *
     * @param remark the value for s_user.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user.menus
     *
     * @return the value of s_user.menus
     *
     * @mbg.generated
     */
    public String getMenus() {
        return menus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user.menus
     *
     * @param menus the value for s_user.menus
     *
     * @mbg.generated
     */
    public void setMenus(String menus) {
        this.menus = menus == null ? null : menus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user.popedom
     *
     * @return the value of s_user.popedom
     *
     * @mbg.generated
     */
    public String getPopedom() {
        return popedom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user.popedom
     *
     * @param popedom the value for s_user.popedom
     *
     * @mbg.generated
     */
    public void setPopedom(String popedom) {
        this.popedom = popedom == null ? null : popedom.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user.avocation
     *
     * @return the value of s_user.avocation
     *
     * @mbg.generated
     */
    public String getAvocation() {
        return avocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user.avocation
     *
     * @param avocation the value for s_user.avocation
     *
     * @mbg.generated
     */
    public void setAvocation(String avocation) {
        this.avocation = avocation == null ? null : avocation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user.strongsuit
     *
     * @return the value of s_user.strongsuit
     *
     * @mbg.generated
     */
    public String getStrongsuit() {
        return strongsuit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user.strongsuit
     *
     * @param strongsuit the value for s_user.strongsuit
     *
     * @mbg.generated
     */
    public void setStrongsuit(String strongsuit) {
        this.strongsuit = strongsuit == null ? null : strongsuit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user.communicate
     *
     * @return the value of s_user.communicate
     *
     * @mbg.generated
     */
    public String getCommunicate() {
        return communicate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user.communicate
     *
     * @param communicate the value for s_user.communicate
     *
     * @mbg.generated
     */
    public void setCommunicate(String communicate) {
        this.communicate = communicate == null ? null : communicate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user.bringup
     *
     * @return the value of s_user.bringup
     *
     * @mbg.generated
     */
    public String getBringup() {
        return bringup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user.bringup
     *
     * @param bringup the value for s_user.bringup
     *
     * @mbg.generated
     */
    public void setBringup(String bringup) {
        this.bringup = bringup == null ? null : bringup.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user.organise
     *
     * @return the value of s_user.organise
     *
     * @mbg.generated
     */
    public String getOrganise() {
        return organise;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user.organise
     *
     * @param organise the value for s_user.organise
     *
     * @mbg.generated
     */
    public void setOrganise(String organise) {
        this.organise = organise == null ? null : organise.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user.analyse
     *
     * @return the value of s_user.analyse
     *
     * @mbg.generated
     */
    public String getAnalyse() {
        return analyse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user.analyse
     *
     * @param analyse the value for s_user.analyse
     *
     * @mbg.generated
     */
    public void setAnalyse(String analyse) {
        this.analyse = analyse == null ? null : analyse.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user.planing
     *
     * @return the value of s_user.planing
     *
     * @mbg.generated
     */
    public String getPlaning() {
        return planing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user.planing
     *
     * @param planing the value for s_user.planing
     *
     * @mbg.generated
     */
    public void setPlaning(String planing) {
        this.planing = planing == null ? null : planing.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user.empolder
     *
     * @return the value of s_user.empolder
     *
     * @mbg.generated
     */
    public String getEmpolder() {
        return empolder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user.empolder
     *
     * @param empolder the value for s_user.empolder
     *
     * @mbg.generated
     */
    public void setEmpolder(String empolder) {
        this.empolder = empolder == null ? null : empolder.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_user.relation
     *
     * @return the value of s_user.relation
     *
     * @mbg.generated
     */
    public String getRelation() {
        return relation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user.relation
     *
     * @param relation the value for s_user.relation
     *
     * @mbg.generated
     */
    public void setRelation(String relation) {
        this.relation = relation == null ? null : relation.trim();
    }
}