package com.bean;

import lombok.Data;

/**
 * @version 2017/6/29.
 * @auther CrazyBunQnQ
 */
@Data
public class UserGroup {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user_group.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user_group.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user_group.principal
     *
     * @mbg.generated
     */
    private String principal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user_group.incumbent
     *
     * @mbg.generated
     */
    private String incumbent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user_group.pid
     *
     * @mbg.generated
     */
    private Integer pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user_group.fcode
     *
     * @mbg.generated
     */
    private String fcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_user_group.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user_group.name
     *
     * @param name the value for s_user_group.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user_group.principal
     *
     * @param principal the value for s_user_group.principal
     *
     * @mbg.generated
     */
    public void setPrincipal(String principal) {
        this.principal = principal == null ? null : principal.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user_group.incumbent
     *
     * @param incumbent the value for s_user_group.incumbent
     *
     * @mbg.generated
     */
    public void setIncumbent(String incumbent) {
        this.incumbent = incumbent == null ? null : incumbent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user_group.fcode
     *
     * @param fcode the value for s_user_group.fcode
     *
     * @mbg.generated
     */
    public void setFcode(String fcode) {
        this.fcode = fcode == null ? null : fcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_user_group.remark
     *
     * @param remark the value for s_user_group.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}